import { createServer as createHttpServer } from 'node:http';
import crypto from 'node:crypto';
import express from 'express';
import QRCode from 'qrcode';
import { WebSocketServer, WebSocket } from 'ws';
import { createMcpHandler, McpServer } from '@modelcontextprotocol/server';
import { toNodeHandler } from '@modelcontextprotocol/node';
import * as z from 'zod';
import type { AgentMessage, AgentRequest, AgentResponse, ToolName } from '../shared/protocol.js';
import { approve, authorizationPage, exchangeToken, oauthMetadata, protectedResourceMetadata, registerClient, getAccessTokenClientId, validAccessToken } from './oauth.js';
import { approveAgent, agentApprovalPage, createAgentApproval, hasAgentGrant, identityFromHello, listAgentIdentities, registerAgent } from './agent-permissions.js';
import { getDb, saveDb } from './db.js';
import { otpauthUri, randomBase32 } from './totp.js';
const PORT=Number(process.env.PORT??8787),AGENT_TOKEN=process.env.AGENT_TOKEN,PUBLIC_URL=(process.env.PUBLIC_URL??'https://bombless.duckdns.org').replace(/\/$/,'');
if(!AGENT_TOKEN)throw new Error('AGENT_TOKEN must be set');
class AgentRegistry{private agents=new Map<string,WebSocket>();private pending=new Map<string,{resolve:(v:unknown)=>void;reject:(e:Error)=>void}>();add(id:string,ws:WebSocket){this.agents.get(id)?.close(4000,'replaced');this.agents.set(id,ws);ws.on('close',()=>{if(this.agents.get(id)===ws)this.agents.delete(id)})}get(id:string){const ws=this.agents.get(id);return ws?.readyState===WebSocket.OPEN?ws:undefined}async call(agentId:string,tool:ToolName,args:Record<string,unknown>){const ws=this.get(agentId);if(!ws)throw new Error(`Windows agent '${agentId}' is not connected`);const id=crypto.randomUUID(),request:AgentRequest={type:'request',id,tool,args};return await new Promise<unknown>((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error('Agent request timed out'))},Number(process.env.REQUEST_TIMEOUT_MS??60000));this.pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});try{ws.send(JSON.stringify(request))}catch(e){clearTimeout(timer);this.pending.delete(id);reject(e instanceof Error?e:new Error(String(e)))}})}handle(m:AgentMessage){if(m.type!=='response')return;const r=m as AgentResponse,p=this.pending.get(r.id);if(!p)return;this.pending.delete(r.id);r.ok?p.resolve(r.result):p.reject(new Error(r.error??'Agent request failed'))}list(){return [...this.agents.keys()]}}
const registry=new AgentRegistry();const resultContent=(v:unknown)=>({content:[{type:'text' as const,text:typeof v==='string'?v:JSON.stringify(v,null,2)}],structuredContent:{result:v}});
function buildMcpServer(clientId:string){const server=new McpServer({name:'chatgpt-windows-bridge',version:'0.4.0'});const agentShape={agentId:z.string().min(1).describe('Persistent agent ID from list_agents'),intent:z.string().optional()};server.registerTool('list_agents',{description:'List connected Windows agents with persistent identity and human-readable computer/user names.',inputSchema:z.object({intent:z.string().optional()}),outputSchema:z.object({result:z.unknown()})},async()=>resultContent(await listAgentIdentities()));const agentTools:ToolName[]=['read_file','write_file','list_directory','move_file','delete_file','execute_powershell','get_system_info','run_npm','run_python','python_job_inspect','python_job_kill','python_jobs','run_node','read_file_range','tail_file','get_file_info','create_directory','copy_file','process_list','kill_process','rg','git','apply_patch','find_files','cdp_version','cdp_list_targets','cdp_call'];for(const name of agentTools)server.registerTool(name,{description:`Run ${name} on one specific Windows agent. If this ChatGPT client has not authorized that agent, returns a one-time authorization URL for the user.`,inputSchema:z.object(agentShape).passthrough(),outputSchema:z.object({result:z.unknown()})},async(args:Record<string,unknown>)=>{const agentId=String(args.agentId);if(!(await hasAgentGrant(clientId,agentId))){const approval=await createAgentApproval(clientId,agentId);return resultContent({authorization_required:true,message:`Please open this one-time link to authorize ${approval.agent.display_name} for this ChatGPT connection, then retry the operation.`,authorization_url:approval.authorization_url,expires_at:approval.expires_at,agent:approval.agent})}return resultContent(await registry.call(agentId,name,args))});server.registerTool('fetch_image_block',{description:'Fetch an image URL as an MCP image block.',inputSchema:z.object({url:z.string().url()}),outputSchema:z.object({result:z.unknown()})},async({url})=>{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);const mime=r.headers.get('content-type')?.split(';')[0]??'image/png',data=Buffer.from(await r.arrayBuffer()).toString('base64');return{content:[{type:'image' as const,data,mimeType:mime}],structuredContent:{result:{mimeType:mime,data}}}});server.registerTool('fetch_image_base64',{description:'Fetch an image URL as Base64.',inputSchema:z.object({url:z.string().url()}),outputSchema:z.object({result:z.unknown()})},async({url})=>{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return resultContent({mimeType:r.headers.get('content-type')?.split(';')[0]??'image/png',base64:Buffer.from(await r.arrayBuffer()).toString('base64')})});server.registerTool('fetch_image_url',{description:'Return an image URL.',inputSchema:z.object({url:z.string().url()}),outputSchema:z.object({result:z.unknown()})},async({url})=>resultContent({url}));return server}
async function mcpClientId(req:express.Request){const token=req.header('authorization')?.startsWith('Bearer ')?req.header('authorization')!.slice(7):undefined;if(!(await validAccessToken(token)))return undefined;return getAccessTokenClientId(token)}
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:false,limit:'64kb'}));app.get('/healthz',(_q,r)=>r.json({ok:true,agents:registry.list()}));app.get('/.well-known/oauth-authorization-server',(_q,r)=>r.json(oauthMetadata()));app.get('/.well-known/oauth-protected-resource',(_q,r)=>r.json(protectedResourceMetadata()));app.post('/oauth/register',async(q,r)=>{try{r.status(201).json(await registerClient(q.body))}catch(e){r.status(400).json({error:'invalid_client_metadata',error_description:String(e)})}});app.get('/oauth/authorize',async(q,r)=>{const x=await authorizationPage(q);r.status(x.status).type('html').send(x.body)});app.post('/oauth/authorize/approve',async(q,r)=>{const x=await approve(q);if(x.location)return r.redirect(302,x.location);r.status(x.status).send(x.body)});app.post('/oauth/token',async(q,r)=>{try{r.json(await exchangeToken(q.body))}catch(e){r.status(400).json({error:String(e instanceof Error?e.message:e)})}});
app.get('/_admin/totp',async(req,res)=>{const ip=req.socket.remoteAddress??'';if(!['127.0.0.1','::1','::ffff:127.0.0.1'].includes(ip))return res.status(404).send('Not found');try{const db=await getDb();let config=db.totp_config;if(!config){const now=Date.now();config={secret:randomBase32(),created_at:now,updated_at:now};db.totp_config=config;await saveDb(db)}const uri=otpauthUri(config.secret,'ChatGPT-MCP','owner');res.json({configured:true,account:'owner',qrDataUrl:await QRCode.toDataURL(uri,{margin:2,width:280})})}catch(e){res.status(500).json({configured:false,error:String(e)})}});
app.get('/agent-permission/authorize/:approvalId',async(q,r)=>{const x=await agentApprovalPage(q.params.approvalId);r.status(x.status).type('html').send(x.body)});app.post('/agent-permission/authorize/:approvalId',async(q,r)=>{const grant=await approveAgent(q.params.approvalId);if(!grant)return r.status(400).send('<h2>Authorization link expired or already used</h2>');r.type('html').send('<h2>Authorized</h2><p>This computer is now authorized for the requesting ChatGPT connection. Return to ChatGPT and retry the operation.</p>')});app.get('/agents',async(q,r)=>{const id=await mcpClientId(q);if(!id)return r.status(401).json({error:'unauthorized'});r.json({agents:await listAgentIdentities()})});app.all('/mcp',async(req,res)=>{const clientId=await mcpClientId(req);if(!clientId)return res.status(401).setHeader('WWW-Authenticate',`Bearer resource_metadata="${PUBLIC_URL}/.well-known/oauth-protected-resource"`).json({error:'unauthorized'});const handler=toNodeHandler(createMcpHandler(()=>buildMcpServer(clientId)));try{const result=handler(req,res,req.body);if(result&&typeof(result as Promise<unknown>).then==='function')void(result as Promise<unknown>).catch(()=>{})}catch(e){if(!res.headersSent)res.status(500).json({error:String(e)})}});
const httpServer=createHttpServer(app),wss=new WebSocketServer({noServer:true});httpServer.on('upgrade',(req,socket,head)=>{if(req.url!=='/agent'||req.headers.authorization!==`Bearer ${AGENT_TOKEN}`)return socket.destroy();wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});wss.on('connection',ws=>{let agentId:string|undefined,initialized=false;ws.on('message',async raw=>{try{const m=JSON.parse(raw.toString()) as AgentMessage;if(m.type==='hello'){if(!/^[a-zA-Z0-9._-]{1,64}$/.test(m.agentId))return ws.close(4002,'invalid agentId');agentId=m.agentId;initialized=true;registry.add(agentId,ws);await registerAgent(identityFromHello(m));return}if(!initialized)return ws.close(4003,'hello required');registry.handle(m)}catch{ws.close(4004,'invalid message')}})});httpServer.listen(PORT,'0.0.0.0',()=>console.log(`agent-perm MCP gateway listening on :${PORT}`));
