import crypto from 'node:crypto';
import { getDb, saveDb } from './db.js';
const PUBLIC_URL = (process.env.PUBLIC_URL ?? 'https://bombless.duckdns.org').replace(/\/$/, '');
const APPROVAL_TTL_MS = Number(process.env.AGENT_APPROVAL_TTL_MS ?? 5 * 60 * 1000);
const GRANT_TTL_MS = Number(process.env.AGENT_GRANT_TTL_MS ?? 30 * 24 * 60 * 60 * 1000);
const random = (bytes = 32) => crypto.randomBytes(bytes).toString('base64url');
export type AgentIdentity = { agent_id:string; hostname:string; username:string; display_name:string; platform:string; version:string; first_seen_at:number; last_seen_at:number };
const safe = (v:unknown, fallback='') => typeof v === 'string' ? v.slice(0,256) : fallback;
export async function registerAgent(identity:Omit<AgentIdentity,'first_seen_at'|'last_seen_at'>) { const db=await getDb(), now=Date.now(), old=db.agents[identity.agent_id]; db.agents[identity.agent_id]={...identity,first_seen_at:old?.first_seen_at??now,last_seen_at:now}; await saveDb(db); return db.agents[identity.agent_id]; }
export async function listAgentIdentities(){ return Object.values((await getDb()).agents); }
export async function createAgentApproval(clientId:string,agentId:string){ const db=await getDb(), agent=db.agents[agentId]; if(!agent) throw new Error(`Unknown agent '${agentId}'`); const approvalId=random(24), now=Date.now(); db.agent_approvals[approvalId]={approval_id:approvalId,agent_id:agentId,client_id:clientId,created_at:now,expires_at:now+APPROVAL_TTL_MS,used:false}; await saveDb(db); return {approval_id:approvalId,authorization_url:`${PUBLIC_URL}/agent-permission/authorize/${encodeURIComponent(approvalId)}`,expires_at:now+APPROVAL_TTL_MS,agent}; }
export async function agentApprovalPage(approvalId:string){ const db=await getDb(), a=db.agent_approvals[approvalId]; if(!a||a.used||a.expires_at<Date.now()) return {status:400,body:'<h2>Authorization link expired</h2><p>Please ask ChatGPT to request a new link.</p>'}; const agent=db.agents[a.agent_id]; if(!agent) return {status:404,body:'<h2>Agent not found</h2>'}; return {status:200,body:`<!doctype html><html><body style="font-family:system-ui,sans-serif;max-width:640px;margin:60px auto;padding:0 18px"><h2>Authorize Windows agent</h2><p>ChatGPT is requesting access to:</p><dl><dt><b>Computer</b></dt><dd>${escapeHtml(agent.display_name)}</dd><dt><b>Username</b></dt><dd>${escapeHtml(agent.username)}</dd><dt><b>Agent ID</b></dt><dd><code>${escapeHtml(agent.agent_id)}</code></dd></dl><p>This authorization applies only to this agent.</p><form method="post" action="/agent-permission/authorize/${encodeURIComponent(approvalId)}"><button style="padding:10px 18px">Authorize this computer</button></form></body></html>`}; }
export async function approveAgent(approvalId:string){ const db=await getDb(), a=db.agent_approvals[approvalId]; if(!a||a.used||a.expires_at<Date.now()) return undefined; a.used=true; const grantId=random(32), now=Date.now(); db.agent_grants[grantId]={grant_id:grantId,agent_id:a.agent_id,client_id:a.client_id,created_at:now,expires_at:now+GRANT_TTL_MS}; await saveDb(db); return db.agent_grants[grantId]; }
export async function hasAgentGrant(clientId:string|undefined,agentId:string){ if(!clientId)return false; return Object.values((await getDb()).agent_grants).some(g=>g.agent_id===agentId&&g.client_id===clientId&&g.expires_at>=Date.now()); }
function escapeHtml(v:string){return v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
export function identityFromHello(m:{agentId:string;hostname:string;username?:string;displayName?:string;platform:string;version:string}){return {agent_id:safe(m.agentId),hostname:safe(m.hostname),username:safe(m.username,'unknown'),display_name:safe(m.displayName,safe(m.hostname,m.agentId)),platform:safe(m.platform),version:safe(m.version)};}
